### ISSUE TITLE
Registry errors

### ISSUE THREAD

**Issue by jeroen** [fastverse/universe#1]
Hello @SebKrantz are you still interested in maintaining this collection?

If so, can you please fix long-term non working packages? There are at least a few in your registry that seem to need a `subdir` field, see the CI errors here: https://github.com/r-universe/fastverse/actions/workflows/sync.yml

Also there are several packages that apparently cannot be built from source as is such as `rJava` and `rsparse`: https://fastverse.r-universe.dev/builds. Can you also remove or fix these packages because the repeated retrying takes up a lot of resources.

**Comment by SebKrantz** [comment]
Thanks @jeroen. Yeah I still need this universe, mainly because the *fastverse* package on CRAN has built-in facilities to update to development versions using this universe. I've removed `rJava` and `rsparse`, and added subdirectories to `fastmatrix` and `nCompiler`.

**Comment by jeroen** [comment]
OK thanks. Can you pls also rename this repo to `fastverse.r-universe.dev` ? See also: https://ropensci.org/blog/2023/02/07/runiverse-registry-repo/

**Comment by SebKrantz** [comment]
Sure, thanks!
